### ISSUE TITLE
Move deps from github.com/ehmry/ to github.com/fc00/

### ISSUE THREAD

**Issue by wstrm** [ehmry/go-cjdns#4]
I'm not sure if this is meant to be the main repository for `go-cjdns`.

But right now you have to `go get` both `github.com/ehmry/go-cjdns` and `github.com/fc00/go-cjdns`.

Would be nice to change all deps from `github.com/ehmry/go-cjdns/...` to `github.com/fc00/go-cjdns/...` instead. [github.com/ehmry/go-cjdns ](https://github.com/ehmry/go-cjdns) points to this repository already anyways.

**Comment by ghost** [comment]
You're absolutely right, this was overlooked! Wanna give it a try? Simple find+replace should be enough
